### ISSUE TITLE
Tag v1.1 release needed

### ISSUE THREAD

**Issue by lrknox** [hpc-io/vol-external-passthrough#6]
The spack package hdf5-vol-external-passthrough installs successfully with the current default hdf5@1.14.0  using "spack install hdf5-vol-external@develop" but has build errors using "spack install hdf5-vol-external".  @houjun, could you apply tag v1.1 to the current develop?

**Comment by houjun** [comment]
done

**Comment by lrknox** [comment]
Thank you!  PR [https://github.com/spack/spack/pull/35309](35309) created for spack update.
